config/routes.rb
Box::Application.routes.draw do

  resources :items, :constraints => { :id => /.*/ }

  root :to => 'items#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "rnaud" && password == "melchi"
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    if params[:dir]
      dir = CGI::unescape(params[:dir])
      dir = dir.gsub(/([\[\]\{\}\*\?\\])/, '\\\\\1')
      puts dir
      logger.info(dir)
      @files = Dir.glob("public/files/#{dir}/*")
    else
      @files = Dir.glob("public/files/*")
    end

      respond_to do |format|
        format.html
      end
  end

  def show
    @file = CGI::unescape(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/files/index.html.erb
<h1>Listing</h1>
<table>
<ul>
<% for file in @files %>
<% new_file = file.to_s.sub('public/files/', "") %>
<% if File.directory?(file) %>
  <li><%= link_to "dir: #{new_file}", params.merge({:dir => new_file}) %></li>
<% else %>
  <li><%= link_to new_file.to_s, "files/#{new_file}" %></li>
<% end %>
<% end %>
</ul>
</table>

app/views/items/index.html.erb
<h1>Listing</h1>
<table>
<ul>
<% for file in @files %>
<% new_file = file.to_s.sub('public/files/', "") %>
<% if File.directory?(file) %>
  <li><%= link_to "dir: #{new_file}", params.merge({:dir => new_file}) %></li>
<% else %>
  <li><%= link_to new_file.to_s, item_path(new_file) %></li>
<% end %>
<% end %>
</ul>
</table>

app/views/items/show.html.erb
<h1><%= @file %></h1>
<div class="flowplayer">
   <video src="<%= "http://#{request.host_with_port}/files/#{@file}" %>"></video>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Box</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" type="text/css" href="http://releases.flowplayer.org/5.1.1/skin/minimalist.css" />
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script src="http://releases.flowplayer.org/5.1.1/flowplayer.min.js"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>